### ISSUE TITLE
The checkpoint file seems to be damaged.

### ISSUE THREAD

**Issue by Hannah458** [ml-jku/clamp#7]
I run the repo code in the readme, and the error is as follow:
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
I located the origin code, then found it is about the checkpoint file. I re-downloaded this file, but it still didn't work. How can I solve this problem?
clamp-main/clamp/models/pretrained.py", line 32, in __init__
    cp = torch.load(self.checkpoint, map_location=device)

**Comment by phseidl** [comment]
Hi,
the file might have been corrupted due to a failed download; just delete the files and re-run the command:
`rm -rf ./data/models/clamp_clip`

running the [colab](https://colab.research.google.com/github/ml-jku/clamp/blob/main/notebooks/CLAMP_colab_demo.ipynb#scrollTo=u7iXYgdmMX6m) example still works.

Best, Philipp
